language: node_js
node_js:
- '6'
before_install:
- npm install babel-cli browserify mocha istanbul -g
install:
- npm install babel-preset-es2015 babel-preset-react
- npm install
script:
- ./ci/compile.js
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
